#include "buzzer.h"

// Reference the TIM4 handle generated by CubeMX
extern TIM_HandleTypeDef htim4;

/* ═══════════════════════════════════════════════════════════════ */
/* CORE PWM FREQUENCY GENERATOR                                    */
/* ═══════════════════════════════════════════════════════════════ */
void Buzzer_PlayTone(uint16_t frequency, uint32_t duration_ms) {
    if (frequency == 0) {
        // Frequency of 0 means silence
        __HAL_TIM_SET_COMPARE(&htim4, TIM_CHANNEL_3, 0);
        HAL_Delay(duration_ms);
        return;
    }

    // Timer runs at 1,000,000 Hz (because Prescaler is 71 on a 72MHz clock).
    // Auto-Reload Register (ARR) = 1,000,000 / Frequency
    uint32_t arr_value = 1000000 / frequency;

    // Set the target frequency
    __HAL_TIM_SET_AUTORELOAD(&htim4, arr_value);

    // Set the duty cycle to 50% for maximum volume (CCR = ARR / 2)
    __HAL_TIM_SET_COMPARE(&htim4, TIM_CHANNEL_3, arr_value / 2);

    // Start the PWM signal on TIM4 Channel 3
    HAL_TIM_PWM_Start(&htim4, TIM_CHANNEL_3);

    // Let the tone play for the designated time
    HAL_Delay(duration_ms);

    // Stop the PWM signal and mute the buzzer
    __HAL_TIM_SET_COMPARE(&htim4, TIM_CHANNEL_3, 0);
    HAL_TIM_PWM_Stop(&htim4, TIM_CHANNEL_3);
}

/* ═══════════════════════════════════════════════════════════════ */
/* CUSTOM SOUND PROFILES                                           */
/* ═══════════════════════════════════════════════════════════════ */

void Buzzer_BootSound(void) {
	// Rapidly slide the frequency from 500Hz up to 2500Hz
	    for (uint16_t freq = 500; freq <= 2500; freq += 100) {
	        Buzzer_PlayTone(freq, 10);
	    }
	    // Cap it off with a solid, sustained high note
	    Buzzer_PlayTone(2500, 150);
}

void Buzzer_WifiConnected(void) {
    // Two crisp, high-pitched chirps
    Buzzer_PlayTone(2000, 80);
    Buzzer_PlayTone(0, 50);      // Short silence
    Buzzer_PlayTone(2500, 150);
}

void Buzzer_WifiDisconnected(void) {
    // A descending, sad "womp-womp" tone
    Buzzer_PlayTone(800, 200);
    Buzzer_PlayTone(400, 400);
}

/* ==================================================================== */
/* UI & SD CARD SOUND PROFILES                                          */
/* ==================================================================== */

void Buzzer_LongPressAck(void) {
    Buzzer_PlayTone(1000, 100); // Acknowledge the long press
}

void Buzzer_FormatSuccess(void) {
    Buzzer_PlayTone(2000, 200); // Success chime
}

void Buzzer_FormatFail(void) {
    Buzzer_PlayTone(400, 500);  // Error drone
}

void Buzzer_SD_Inserted(void) {
    Buzzer_PlayTone(2000, 100); // Quick high-pitch chime for hot-swap
}

void Buzzer_SD_Removed(void) {
    // A sharp, low-pitched double beep to warn of hardware removal
    Buzzer_PlayTone(300, 150);
    Buzzer_PlayTone(0, 50);
    Buzzer_PlayTone(300, 150);
}
