#include "dust.h"
#include "main.h"

// External handles generated by CubeMX
extern ADC_HandleTypeDef hadc1;

uint16_t dust_raw_adc = 0;
float dust_raw_voltage = 0.0f;

void initDustSensor(void) {
    // Ensure ADC is calibrated
    HAL_ADCEx_Calibration_Start(&hadc1);
}

int16_t readDust(void) {
    // 1. Pull LED LOW (Turn on IR LED)
    HAL_GPIO_WritePin(DUST_LED_GPIO_Port, DUST_LED_Pin, GPIO_PIN_RESET);

    // 2. Wait exactly 280us (Sampling timing mandated by Sharp datasheet)
    uint32_t cycles = 280 * (SystemCoreClock / 1000000);
    uint32_t start = DWT->CYCCNT;
    while((DWT->CYCCNT - start) < cycles);

    // 3. ROCK-SOLID POLLING READ (No DMA)
    HAL_ADC_Start(&hadc1);
    HAL_ADC_PollForConversion(&hadc1, 10);      // Wait for conversion to finish
    uint16_t raw_val = HAL_ADC_GetValue(&hadc1); // Grab the 0-4095 value directly
    HAL_ADC_Stop(&hadc1);

    // 4. Wait 40us to hit the required 0.32ms pulse width before turning off
    cycles = 40 * (SystemCoreClock / 1000000);
    start = DWT->CYCCNT;
    while((DWT->CYCCNT - start) < cycles);

    // 5. Pull LED HIGH (Turn off IR LED)
    HAL_GPIO_WritePin(DUST_LED_GPIO_Port, DUST_LED_Pin, GPIO_PIN_SET);

    // 6. Convert to Voltage (12-bit = 4095, 3.3V Reference)
    float voltage = (raw_val * 3.3f) / 4095.0f;

    // 7. Apply Non-Blocking Exponential Moving Average (EMA) Filter
    // Seeds the filter with the exact median no-dust voltage to prevent initial drops
    static float filtered_voltage = 0.77f;
    filtered_voltage = (filtered_voltage * 0.8f) + (voltage * 0.2f);

    // 8. Calculate Dust Density (ug/m3)
    // - Base Voltage (Voc) = 0.77V (Extracted from ClimateLogs.csv)
    // - Sensitivity = 200 ug/m3 per 1.0V (Extracted from Sharp Datasheet)
    float dustDensity = (filtered_voltage - 0.77f) * 200.0f;

    if (dustDensity < 0) {
        dustDensity = 0;
    }

    // 9. Push data to the global variables for the OLED Debug Page
    dust_raw_adc = raw_val;
    dust_raw_voltage = filtered_voltage;

    // Return x10 to preserve 1 decimal place for the UI
    return (int16_t)(dustDensity * 10.0f);
}
